export const categories = [
  { id: "all", name: "Todos" },
  { id: "hidraulicos", name: "Hidráulicos" },
  { id: "eletricos", name: "Elétricos" },
  { id: "pinturas", name: "Pinturas" },
  { id: "equipamentos", name: "Equipamentos" },
];

export const products = [
  {
    id: "tigre-tubo-soldavel-3m",
    category: "hidraulicos",
    name: "Tubo Soldável Tigre 25 mm 3 m",
    brand: "Tigre",
    sku: "HID-TIG-25-3",
    price: 28.9,
    stock: 42,
    image: "https://qfzo0q7soc.execute-api.us-east-1.amazonaws.com/master/new/media/catalog/product//1/0/10121744_tubo_sold_vel_3m_iso.jpg",
    specs: ["PVC rígido para água fria", "Uso residencial, comercial e industrial", "Produto de linha Tigre"],
  },
  {
    id: "tigre-tubo-soldavel-6m",
    category: "hidraulicos",
    name: "Tubo Soldável Tigre 25 mm 6 m",
    brand: "Tigre",
    sku: "HID-TIG-25-6",
    price: 54.9,
    stock: 31,
    image: "https://qfzo0q7soc.execute-api.us-east-1.amazonaws.com/master/new/media/catalog/product//1/0/10120209_tubo_sold_vel_6m_iso.jpg",
    specs: ["Barra com 6 metros", "Indicado para instalações de água fria", "Leve e resistente"],
  },
  {
    id: "tigre-luva-correr",
    category: "hidraulicos",
    name: "Luva de Correr Tigre para Tubo Soldável",
    brand: "Tigre",
    sku: "HID-TIG-LC",
    price: 22.9,
    stock: 36,
    image: "https://qfzo0q7soc.execute-api.us-east-1.amazonaws.com/master/new/media/catalog/product//l/u/luva.jpg",
    specs: ["Reparo rápido em tubulações", "Dispensa rosca", "Aplicação em água fria"],
  },
  {
    id: "tigre-adesivo-frasco",
    category: "hidraulicos",
    name: "Adesivo PVC Frasco Tigre 175 g",
    brand: "Tigre",
    sku: "HID-TIG-ADS-F",
    price: 17.5,
    stock: 95,
    image: "https://qfzo0q7soc.execute-api.us-east-1.amazonaws.com/master/new/media/catalog/product//3/f/3f44e4cb9a632995d45a7ec8f6983484.png",
    specs: ["Indicado para conexões soldáveis", "Frasco 175 g", "Uso em instalações hidráulicas"],
  },
  {
    id: "tigre-adesivo-bisnaga",
    category: "hidraulicos",
    name: "Adesivo PVC Bisnaga Tigre",
    brand: "Tigre",
    sku: "HID-TIG-ADS-B",
    price: 9.9,
    stock: 118,
    image: "https://qfzo0q7soc.execute-api.us-east-1.amazonaws.com/master/new/media/catalog/product//d/1/d1efcce1e7b195d2d45796fb70447da9.jpg",
    specs: ["Formato bisnaga", "Aplicação prática", "Ideal para pequenos reparos"],
  },
  {
    id: "steck-disjuntor-32a",
    category: "eletricos",
    name: "Disjuntor Bipolar DIN Steck 32 A",
    brand: "Steck",
    sku: "ELE-STE-32",
    price: 39.9,
    stock: 64,
    image: "https://dimensionalstoreb2b.vtexassets.com/arquivos/ids/215400/Disjuntor-bipolar-32a-SDD62C32-2.png?v=638319493099300000",
    specs: ["Curva C", "Instalação em trilho DIN", "Proteção para circuitos residenciais"],
  },
  {
    id: "sil-cabo-flexivel",
    category: "eletricos",
    name: "Cabo Flexsil SIL 2,5 mm 100 m",
    brand: "Sil",
    sku: "ELE-SIL-25100",
    price: 189.9,
    stock: 18,
    image: "https://cdn.awsli.com.br/800x800/2240/2240977/produto/351627415/ffe08aad6ccb403c91ed473e0f5bed69-product-images-8771042-30425dab71544f5fa3b9b1a8-whtao05hzg.png",
    specs: ["Rolo com 100 metros", "750 V", "Cobre flexível"],
  },
  {
    id: "avant-lampada-led",
    category: "eletricos",
    name: "Lâmpada LED Bulbo Avant 9 W 6500 K",
    brand: "Avant",
    sku: "ELE-AVA-9W",
    price: 8.9,
    stock: 122,
    image: "https://cdn.awsli.com.br/800x800/1821/1821377/produto/114027606/733a3dc3e3.jpg",
    specs: ["810 lumens", "Luz branca fria", "Baixo consumo"],
  },
  {
    id: "tramontina-tomada-dupla",
    category: "eletricos",
    name: "Tomada Dupla Tramontina Lux2 10 A",
    brand: "Tramontina",
    sku: "ELE-TRA-2T10",
    price: 24.9,
    stock: 57,
    image: "https://lojaacal.vtexassets.com/arquivos/ids/163083/conjunto-de-2-tomadas-energia-10a-branco-lux-tramontina-479974.jpg?v=637372615063300000",
    specs: ["2P+T 10 A", "Módulo 4x2", "Acabamento branco"],
  },
  {
    id: "tigre-eletroduto",
    category: "eletricos",
    name: "Eletroduto Soldável Tigre",
    brand: "Tigre",
    sku: "ELE-TIG-ELET",
    price: 18.9,
    stock: 76,
    image: "https://qfzo0q7soc.execute-api.us-east-1.amazonaws.com/master/new/media/catalog/product//1/4/14130209_eletroduto_sold_vel_iso.jpg",
    specs: ["PVC antichama", "Uso em instalações elétricas", "Alta resistência mecânica"],
  },
  {
    id: "suvinil-verniz-acrilico",
    category: "pinturas",
    name: "Suvinil Verniz Acrílico 3,6 L",
    brand: "Suvinil",
    sku: "PIN-SUV-VA36",
    price: 170.9,
    stock: 11,
    image: "https://digitalprdaddc4dsa.blob.core.windows.net/digital-products-img/products/8/image/display/36/1.webp?sv=2026-02-06&spr=https&st=2026-05-13T06%3A09%3A38Z&se=2026-06-12T06%3A14%3A38Z&sr=b&sp=r&sig=wxIWv3Ru1DowYfCvw4Q4RZquSYoCh%2F%2Byy0nDId0E%2FlA%3D",
    specs: ["Acabamento brilhante", "Impermeabiliza superfícies", "Uso interno e externo"],
  },
  {
    id: "suvinil-massa-acrilica",
    category: "pinturas",
    name: "Suvinil Massa Acrílica",
    brand: "Suvinil",
    sku: "PIN-SUV-MA",
    price: 89.9,
    stock: 24,
    image: "https://digitalprdaddc4dsa.blob.core.windows.net/digital-products-img/products/89/image/display/11/1.webp?sv=2026-02-06&spr=https&st=2026-05-13T16%3A29%3A58Z&se=2026-06-12T16%3A34%3A58Z&sr=b&sp=r&sig=IiOZUBnjkXy509V4KDiLKQpZLY6P7BdoeB2VuwajtF0%3D",
    specs: ["Nivela superfícies", "Indicada para áreas úmidas", "Prepara parede para pintura"],
  },
  {
    id: "suvinil-massa-corrida",
    category: "pinturas",
    name: "Suvinil Massa Corrida",
    brand: "Suvinil",
    sku: "PIN-SUV-MC",
    price: 74.9,
    stock: 37,
    image: "https://digitalprdaddc4dsa.blob.core.windows.net/digital-products-img/products/88/image/display/82/1.webp?sv=2026-02-06&spr=https&st=2026-05-15T11%3A02%3A28Z&se=2026-06-14T11%3A07%3A28Z&sr=b&sp=r&sig=xvS9qwPI5y2ItwGm9QNjdYP2WXYHTYbWu7075i7%2BdZs%3D",
    specs: ["Uso interno", "Acabamento liso", "Aplicação com desempenadeira ou espátula"],
  },
  {
    id: "suvinil-selador-acrilico",
    category: "pinturas",
    name: "Suvinil Selador Acrílico",
    brand: "Suvinil",
    sku: "PIN-SUV-SA",
    price: 96.9,
    stock: 21,
    image: "https://digitalprdaddc4dsa.blob.core.windows.net/digital-products-img/products/92/image/display/36/1.webp?sv=2026-02-06&spr=https&st=2026-05-13T06%3A21%3A46Z&se=2026-06-12T06%3A26%3A46Z&sr=b&sp=r&sig=WfuJVk8L%2BP%2BxnRfaLuZnylFB6VvGMoNHMZ6TjWoMJW8%3D",
    specs: ["Prepara parede nova", "Uniformiza absorção", "Aumenta rendimento da tinta"],
  },
  {
    id: "jotun-facade",
    category: "pinturas",
    name: "Jotun Facade Powder Coatings",
    brand: "Jotun",
    sku: "PIN-JOT-FAC",
    price: 412.9,
    stock: 8,
    image: "https://cp.jotun.com/siteassetsjot03/_b2b/product-logos-30.11.21/powder-box-image/jotun-box-closed.png?format=webp&quality=70&width=1408",
    specs: ["Linha para fachadas", "Resiste a intempéries", "Acabamento técnico"],
  },
  {
    id: "bosch-parafusadeira",
    category: "equipamentos",
    name: "Parafusadeira/Furadeira Bosch GSB 120-LI",
    brand: "Bosch",
    sku: "EQP-BOS-120",
    price: 349.9,
    stock: 7,
    image: "https://cdn.awsli.com.br/800x800/2820/2820925/produto/355011478/blob-w2gfmlboua.jpg",
    specs: ["Bateria 12 V", "Acompanha maleta", "Uso profissional e manutenção"],
  },
  {
    id: "makita-hp1640",
    category: "equipamentos",
    name: "Furadeira de Impacto Makita HP1640 760 W",
    brand: "Makita",
    sku: "EQP-MAK-1640",
    price: 389.9,
    stock: 13,
    image: "https://images.tcdn.com.br/img/img_prod/1114348/furadeira_martelete_parafusadeira_eletrica_de_1_2_makita_hp1640_760w_hp1640_220v_695_1_160a9a848f0d30b3ce8cafaffc10c163.jpg",
    specs: ["760 W", "Mandril 1/2 pol.", "Rotação com impacto"],
  },
  {
    id: "volk-luva-nitrilica",
    category: "equipamentos",
    name: "Luva Nitrílica Volk Proteção Química",
    brand: "Volk",
    sku: "EQP-VOL-LVQ",
    price: 16.9,
    stock: 48,
    image: "https://dimensionalstoreb2b.vtexassets.com/arquivos/ids/306278/nitrilica-sem-forro-verde-copy1.jpg?v=638291813350300000",
    specs: ["Borracha nitrílica", "Proteção contra agentes químicos", "Palma antiderrapante"],
  },
  {
    id: "mor-escada-5",
    category: "equipamentos",
    name: "Escada de Alumínio Mor 5 Degraus",
    brand: "Mor",
    sku: "EQP-MOR-5103",
    price: 189.9,
    stock: 9,
    image: "https://ghaus.vtexassets.com/arquivos/ids/207409/escada-de-aluminio-residencial-mor-5-degraus_01.jpg?v=638646215815230000",
    specs: ["Alumínio leve", "Uso doméstico e manutenção", "5 degraus"],
  },
  {
    id: "tramontina-alicate",
    category: "equipamentos",
    name: "Alicate Universal Tramontina 8 pol.",
    brand: "Tramontina",
    sku: "EQP-TRA-AL8",
    price: 54.9,
    stock: 34,
    image: "https://assets.tramontina.com.br/upload/tramon/imagens/GAR/41001108PDM001G.jpg",
    specs: ["Cabo isolado", "Uso elétrico e manutenção", "Aço especial"],
  },
];

export const currency = new Intl.NumberFormat("pt-BR", {
  style: "currency",
  currency: "BRL",
});

export const sviLinks = {
  instagram: "https://instagram.com",
  facebook: "https://facebook.com",
  jobs: "https://svinstalacoes.vagas.solides.com.br",
  collaborator: "https://svinstalacoes.com.br",
  whatsapp: "https://wa.me/559221234411",
};
